name: Princess Sketch Comedy
favicon: null
layout_spectrum: 0.99734
typography_spectrum: 0.14895
title: Princess Sketch Comedy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7fc788'
    - '#1a1a24'
    - '#f5ef00'
    - '#e34e85'
    - '#00a3bd'
  brandStrength: 0.7293195088859648
  lightness: 0.6726314735133201
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
