name: Princess Sketch Comedy
favicon: null
layout_spectrum: 0.99734
typography_spectrum: 0.14895
title: Princess Sketch Comedy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1fffb'
    - '#000000'
    - '#e03190'
    - '#f882bf'
    - '#9f9f9f'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 1
purpose: []
